// Copyright (c) Microsoft. All rights reserved. 
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />
namespace Microsoft.Its.Domain.Sql.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v0_9_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v0_9_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201409182131143_v0_9_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
