// <auto-generated />
namespace Microsoft.Its.Domain.Sql.CommandScheduler.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v0_6_12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v0_6_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201404242201400_v0_6_12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
