// Copyright (c) Microsoft. All rights reserved. 
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Reflection;

[assembly: AssemblyVersion("0.8.0.0")]
[assembly: AssemblyFileVersion("0.10.3-beta")]

// Generated by the MSBuild WriteCodeFragment class on 5/29/2014 8:37:06 AM.

